In [19]:
import numpy as np

Using	the	NumPy	array	we	can	quickly	derive	a	vector	and	a	matrix.	If	you	start	from	a Python	list,	you	will	get	a	vector	(which	is	neither	a	row	nor	a	column	vector,	actually). By	using	the	reshape	method,	you	can	transform	it	into	a	row	or	column	vector,	based	on your	specifications. 

In [3]:
vector = np.array([1,2,3,4,5])
row_vector = vector.reshape((5,1))
column_vector = vector.reshape((1,5))
single_feature_matrix = vector.reshape((1,5))


In [6]:
row_vector

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [7]:
column_vector

array([[1, 2, 3, 4, 5]])

In [8]:
multiple_feature_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10], [11,12,13,14,15]])
multiple_feature_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
multiple_feature_matrix = \ 
np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

SyntaxError: unexpected character after line continuation character (<ipython-input-18-9ad441742538>, line 1)

In [15]:
all_zeros = np.zeros((5,3))
all_ones = np.ones((5,3))
all_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
all_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])